#!/bin/sh
#
# 提交信息校验规则 —— 单一事实来源
#
# 被 commit-msg 钩子 source。规则集中在这里，改动只需改这一个文件。
#
# 兼容性：POSIX sh（dash / ash / busybox / bash / zsh），
#        Linux / macOS(BSD 工具链) / Windows(Git for Windows 的 MSYS2 sh)。
#        不使用 local、数组、[[ ]]、echo -e 等非 POSIX 特性。
#
# 接口:
#   validate_commit_msg "<完整提交信息>"
#     返回 0 = 合规，1 = 不合规
#     不合规时错误项写入全局变量 VALIDATE_ERRORS（每行一条）

# ---------------------------------------------------------------- 可配置项
#
# 允许的 type。增删类型改这里，用 | 分隔。
COMMIT_TYPES='feat|fix|docs|style|refactor|test|chore|ci|perf|revert|build'

# subject 最大长度（按字符计，一个汉字算 1）
COMMIT_SUBJECT_MAX=50

# 是否要求 Header 与正文之间有空行：1 要求，0 不要求
COMMIT_REQUIRE_BLANK_LINE=1

# 是否要求英文 subject 首字母小写：1 要求，0 不要求
COMMIT_REQUIRE_LOWERCASE=1

# 以上四项也可以在仓库里用 git config 覆盖，见 load_commit_config()

# ---------------------------------------------------------------- 内部实现

# 从 git config 读取项目自定义配置（可选）
#
#   git config commit-convention.types "feat|fix|custom"
#   git config commit-convention.subjectMax 72
#   git config commit-convention.requireBlankLine false
#   git config commit-convention.requireLowercase false
load_commit_config() {
	command -v git >/dev/null 2>&1 || return 0

	_v=$(git config --get commit-convention.types 2>/dev/null)
	[ -n "$_v" ] && COMMIT_TYPES="$_v"

	_v=$(git config --get commit-convention.subjectMax 2>/dev/null)
	case "$_v" in
		''|*[!0-9]*) ;;                      # 空或非数字则忽略
		*) COMMIT_SUBJECT_MAX="$_v" ;;
	esac

	_v=$(git config --get commit-convention.requireBlankLine 2>/dev/null)
	case "$_v" in false|0|no) COMMIT_REQUIRE_BLANK_LINE=0 ;; esac

	_v=$(git config --get commit-convention.requireLowercase 2>/dev/null)
	case "$_v" in false|0|no) COMMIT_REQUIRE_LOWERCASE=0 ;; esac

	unset _v
	return 0
}

# 统计 UTF-8 字符数（不是字节数）
#
# 不能用 `wc -m`：它的行为取决于 locale——在 LC_ALL=C / LANG=C 下按字节统计，
# 一个汉字算 3，于是 17 个汉字就误判超限。而 git hook 的执行环境、Windows
# 的 Git Bash、CI 容器的默认 locale 恰恰常常是 C。
# 也不能用 awk length()：同样在 C locale 下退化为字节数。
#
# 这里的做法与 locale 完全无关：UTF-8 每个字符有且仅有一个首字节，
# 续字节固定落在 0x80-0xBF，删掉所有续字节后剩余长度即字符数。
utf8_len() {
	printf '%s' "$1" | LC_ALL=C tr -d '\200-\277' | LC_ALL=C wc -c | tr -d ' \n'
}

# 剥离 git 注释行与 verbose 模式（git commit -v）附带的 diff
strip_commit_comments() {
	sed '/^# *-\{1,\} *>8 *-\{1,\}/,$d' | sed '/^#/d'
}

# 判断是否为 git 自动生成的提交（Merge / Revert / autosquash），这类放行
is_autogenerated_commit() {
	case "$1" in
		"Merge "*|"Revert \""*|"fixup!"*|"squash!"*|"amend!"*) return 0 ;;
	esac
	return 1
}

validate_commit_msg() {
	_msg="$1"
	VALIDATE_ERRORS=''

	_add_err() {
		VALIDATE_ERRORS="${VALIDATE_ERRORS}$1
"
	}

	if [ -z "$(printf '%s' "$_msg" | tr -d '[:space:]')" ]; then
		_add_err '提交信息为空'
		return 1
	fi

	# 去掉开头的空行后取第一行作为 Header
	_msg=$(printf '%s\n' "$_msg" | sed -e '/./,$!d')
	_header=$(printf '%s\n' "$_msg" | sed -n '1p')

	is_autogenerated_commit "$_header" && return 0

	if ! printf '%s' "$_header" \
		| grep -Eq "^($COMMIT_TYPES)(\([a-zA-Z0-9_./,-]+\))?: .+$"
	then
		# 细分失败原因，给出可操作的提示
		if ! printf '%s' "$_header" | grep -Eq '^[a-zA-Z]+(\(.*\))?:'; then
			_add_err 'Header 缺少 "<type>: " 前缀'
		elif ! printf '%s' "$_header" | grep -Eq "^($COMMIT_TYPES)(\(.*\))?:"; then
			_bad=$(printf '%s' "$_header" | sed -n 's/^\([a-zA-Z]*\).*/\1/p')
			_add_err "type \"${_bad}\" 不在允许列表中"
		elif printf '%s' "$_header" | grep -Eq "^($COMMIT_TYPES)\(\)"; then
			_add_err 'scope 括号不能为空，不需要 scope 时请省略括号'
		elif printf '%s' "$_header" | grep -Eq "^($COMMIT_TYPES)(\(.*\))?: *$"; then
			_add_err 'subject 不能为空'
		elif printf '%s' "$_header" | grep -Eq "^($COMMIT_TYPES)(\(.*\))?:[^ ]"; then
			_add_err '冒号后必须有一个空格'
		else
			_add_err 'scope 只允许字母、数字和 _ . / , - 字符'
		fi
	else
		_subject=$(printf '%s' "$_header" | sed -E "s/^($COMMIT_TYPES)(\([^)]+\))?: //")

		_len=$(utf8_len "$_subject")
		if [ "$_len" -gt "$COMMIT_SUBJECT_MAX" ]; then
			_add_err "subject 长度 ${_len} 字符，超过 ${COMMIT_SUBJECT_MAX} 字符上限（详细内容请写到正文）"
		fi

		case "$_subject" in
			*.|*。) _add_err 'subject 结尾不要加句号' ;;
		esac

		# 仅当 subject 以英文字母开头时要求首字母小写；中文描述不受此限
		if [ "$COMMIT_REQUIRE_LOWERCASE" = "1" ] \
			&& printf '%s' "$_subject" | grep -q '^[A-Z]'
		then
			_add_err 'subject 首字母请小写（英文描述用现在时动词开头，如 add / fix）'
		fi
	fi

	# Header 与正文之间必须空行
	if [ "$COMMIT_REQUIRE_BLANK_LINE" = "1" ]; then
		_line2=$(printf '%s\n' "$_msg" | sed -n '2p')
		if [ -n "$(printf '%s' "$_line2" | tr -d '[:space:]')" ]; then
			_add_err 'Header 与正文之间必须有一个空行'
		fi
	fi

	[ -z "$VALIDATE_ERRORS" ]
}

# 规范说明文本，供钩子在报错时打印
# $1 / $2 为可选的着色前缀与重置串
print_commit_convention() {
	_c="${1:-}"
	_r="${2:-}"
	cat <<EOF

${_c}正确格式：${_r}
  <type>(<scope>): <subject>
                              <- 空行
  [可选正文：说明变更原因、方案、测试场景]
                              <- 空行
  [可选脚注：Closes #101 / Refs #205]

${_c}type 取值：${_r}
  feat      新功能或优化              fix       修复 Bug
  docs      文档更新                  style     代码格式调整（不影响逻辑）
  refactor  重构（无功能变更）        test      测试相关变更
  chore     构建或工具链变更          ci        持续集成配置变更
  perf      性能优化                  revert    回退提交
  build     构建系统/依赖变更

${_c}示例：${_r}
  feat(user-module): 添加用户注册功能

  - 实现注册接口及前端表单
  - 增加密码加密逻辑

  Closes #101

${_c}规则要点：${_r}
  * type 必选；scope 可选，填模块名/组件名
  * subject 必选，不超过 ${COMMIT_SUBJECT_MAX} 字符，首字母小写，结尾不加句号
  * 英文 subject 用现在时动词开头（add / fix / update，而非 added / fixes）
EOF
}
